# Generated by Django 3.0.2 on 2020-02-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentchange',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='follows', to='uks_app.Profile'),
        ),
    ]
