# Generated by Django 3.0.2 on 2020-02-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lableevent',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uks_app.Label'),
        ),
        migrations.CreateModel(
            name='SubIssueEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uks_app.Event')),
                ('state', models.CharField(choices=[('CR', 'Created'), ('RE', 'Removed')], max_length=2)),
                ('subissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uks_app.Issue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uks_app.event',),
        ),
    ]
