# Generated by Django 3.0.2 on 2020-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='issue',
            field=models.ManyToManyField(related_name='milestones', to='uks_app.Issue'),
        ),
    ]
