# Generated by Django 3.0.2 on 2020-01-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkpoint',
            new_name='Milestone',
        ),
        migrations.RenameModel(
            old_name='CheckpointChange',
            new_name='MilestoneChange',
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='observedproject',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='label',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uks_app.Issue'),
        ),
        migrations.AlterField(
            model_name='statechange',
            name='newState',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=6),
        ),
    ]
