# Generated by Django 3.0.2 on 2020-02-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentchange',
            options={'ordering': ['time']},
        ),
    ]
