# Generated by Django 3.0.2 on 2020-02-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0002_auto_20200212_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='parent_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subissues', to='uks_app.Issue'),
        ),
    ]
