# Generated by Django 3.0.2 on 2020-01-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0002_auto_20200130_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedproject',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
