# Generated by Django 3.0.2 on 2020-01-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0002_auto_20200131_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='project',
            new_name='issue',
        ),
    ]
