# Generated by Django 3.0.2 on 2020-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0002_milestone_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
