# Generated by Django 3.0.2 on 2020-01-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0002_auto_20200130_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uks_app.Issue'),
            preserve_default=False,
        ),
    ]
