# Generated by Django 3.0.2 on 2020-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0003_auto_20200131_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='issue',
        ),
        migrations.AddField(
            model_name='label',
            name='issue',
            field=models.ManyToManyField(to='uks_app.Issue'),
        ),
    ]
