# Generated by Django 3.0.2 on 2020-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0003_auto_20200207_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonechange',
            name='add',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
