# Generated by Django 3.0.2 on 2020-02-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0004_remove_milestonechange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uks_app.Issue'),
            preserve_default=False,
        ),
    ]
